### ISSUE TITLE
openblas dependency issue

### ISSUE THREAD

**Issue by khallock** [conda-forge/ncl-feedstock#12]
There seems to be a problem resolving dependencies when creating a clean environment with only NCL installed:
```
$ ncl
dyld: Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/hallock/miniconda2/envs/ncl-py22/bin/ncl
  Reason: image not found
```

same issue on Linux:
```
$ ncl
ncl: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
```

I looked at the [Travis CI build log](https://travis-ci.org/conda-forge/ncl-feedstock/jobs/240781141) and noticed that the package is being built with `gsl:             2.2.1-blas_openblas_2         conda-forge [blas_openblas]`, `numpy:           1.12.1-py36_blas_openblas_200 conda-forge [blas_openblas]`, and `openblas:        0.2.19-2                      conda-forge`. However, when I install the package on my machine, I get the non-blas versions of `gsl` and `numpy`, and `openblas` is not installed. Installing `openblas` fixes the issue, but I'm not sure why the package is being built one way and then installed the other. For what it's worth, I discovered this due to a bug report from an NCL user, so I'm sure this will affect other users in the near future.

**Comment by ocefpaf** [comment]
A quick work around would be to install `openblas`, but conda should pull the right `gsl` when conda-forge channel is preferred :unamused: 

We can also add `openblas` as a dependency in the `ncl` feedstock, but that is quite annoying b/c IMO conda is not doing the right thing there. I opened #13 to check what packages will be chosen if we re-build `ncl` and if the `openblas` will be downloaded there.

**Comment by ocefpaf** [comment]
Fixed in #13

**Comment by khallock** [comment]
We've received reports of ongoing issues with gsl/blas when installing ncl, but it only seems to affect Mac users:
```$ ncl
dyld: Library not loaded: @rpath/libgsl.19.dylib
  Referenced from: /Users/hallock/miniconda2/envs/blas_issue/bin/ncl
  Reason: Incompatible library version: ncl requires version 22.0.0 or later, but libgsl.19.dylib provides version 20.0.0```

**Comment by ocefpaf** [comment]
Looking into it...

**Comment by khallock** [comment]
Thanks, @ocefpaf!
