### ISSUE TITLE
Try to recompile in 2023

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/ncl-feedstock#146]

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
#144 was green just back in September, but yeah, that's forever ago with conda-forge :)

**Comment by hmaarrfk** [comment]
sometimes i download the logs, delete up to the first `Z `, then use vimdiff

**Comment by zklaus** [comment]
Done in #148. Please reopen if you disagree!
