### ISSUE TITLE
kealib dependency issue

### ISSUE THREAD

**Issue by andreas-h** [conda-forge/ncl-feedstock#18]
The `ncl` executable is linked against kealib 1.4.7:

	libkea.so.1.4.7 => /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/envs/ncl_test/bin/../lib/./libkea.so.1.4.7 (0x00007f6d163a4000)

However, kealib is not explicitly mentioned as dependency in the build recipe.  Since the latest kealib in the *defaults* channel is 1.4.5, this leads to the problem that when I just to `conda create -n ncl_test ncl`, kealib 1.4.5 is being installed, which leads to `ncl` not running.

**Comment by ocefpaf** [comment]
> However, kealib is not explicitly mentioned as dependency in the build recipe

And should not. It is the dependency of a dependency (`gdal`).

> Since the latest kealib in the *defaults* channel is 1.4.5, this leads to the problem that when I just to `conda create -n ncl_test ncl`, kealib 1.4.5 is being installed, which leads to `ncl` not running.

Explicitly listed or not this problem will exist. See https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels for the solution.

**Comment by isuruf** [comment]
> And should not. It is the dependency of a dependency (gdal).

If it's the dependency of a dependency, then it should not be linking against it directly. Maybe adding `-Wl,-as-needed` (On LInux) and `-Wl,-dead_strip_dylibs` (On OSX) will drop the direct linking.

**Comment by ocefpaf** [comment]
I can try that but I never really bothered b/c, when the channels are properly configure it is not needed.

**Comment by isuruf** [comment]
Btw, `libgdal` needs to pin to `kealib 1.4.7`

**Comment by ocefpaf** [comment]
> Btw, `libgdal` needs to pin to `kealib 1.4.7`

I'll leave that to @gillins who is the author of `kealib` and the maintainer of `libgdal` to. I'm sure he is on top of things there.

**Comment by andreas-h** [comment]
In principle I agree.  However, I always run into trouble when trying to
use conda-forge for everything, because different packages are
maintained by different parties who are or aren't up-to-date on
releasing.  I constantly have trouble with libjpeg dependencies in
combination with netcdf4, for example ...  So if there is a possibility
to reduce these dependency issues, that'd be great.

**Comment by ocefpaf** [comment]
> because different packages are
maintained by different parties who are or aren't up-to-date on
releasing

The is not the issue. The issue is a mismatch with `defaults` and `conda-forge`.

> So if there is a possibility to reduce these dependency issues, that'd be great.

We are working towards better compatibility between `conda-forge` and `defaults`, but that will take a while. For now only https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels can help.

**Comment by isuruf** [comment]
> The is not the issue. The issue is a mismatch with defaults and conda-forge.

It is this case, but I recommend doing a pinning here or removing direct linking. It's coincidence that there's no version of  `ncl` and `kealib<1.4.7` with the same hdf5 pinning. Otherwise we could have had a broken environment.

**Comment by ocefpaf** [comment]
> It is this case

I don't think so b/c if you env is set correctly the right `kealib` will be installed.

Anyway, a pinning would help for sure but I believe our efforts should be on conda-build 3 and not fixing individual pinnings.

**Comment by isuruf** [comment]
> I don't think so b/c if you env is set correctly the right kealib will be installed.

How? No package pins `kealib`.

**Comment by ocefpaf** [comment]
> How? No package pins `kealib`.

You don't need the pin to get the latest and nothing pin to the old one. Latest is default in the solver. The issue here is that only the old version is present in `defaults`.

**Comment by isuruf** [comment]
There's `kealib=1.4.6` and `kealib=1.4.7` in conda-forge

**Comment by ocefpaf** [comment]
> There's `kealib=1.4.6` and `kealib=1.4.7` in conda-forge

Yep, and they are compatible. See @gillins trick in the feedstock.
