### ISSUE TITLE
conda-Installed NCL doesn't look for the library correctly

### ISSUE THREAD

**Issue by fischcheng** [conda-forge/ncl-feedstock#19]
It's wonderful to have NCL available on conda! I removed my old binary-installed NCL, and switched to conda version. However, it doesn't look for the $NCARGROOT correctly, keeps referencing to my old directory. I had to reset $NCARGROOT to anaconda root so that ncl can find the lib. Is that a usual behavior? Or this conda/NCL is specifically fo packages like PyNGL and PyNIO, and not supposed to work like the stand-alone version? Thanks!

**Comment by ocefpaf** [comment]
> Is that a usual behavior?

Yes. `conda` has a its own way of setting environment variables to ensure things will work "out of the box."

> Or this conda/NCL is specifically for packages like PyNGL and PyNIO, and not supposed to work like the stand-alone version?

Not really. I don't know the details on how that environmental variable is used across NCAR libraries but it should work as long as everything is installed `conda` while you still can "hack" it to make it work in a different way. (Although the latter is not advisable.)

 See https://github.com/conda-forge/ncl-feedstock/blob/master/recipe/scripts/activate.sh for the details on what is done to `NCARGROOT`. Hopefully that will clarify what is happening and you'll find a way to make it work for your case. (The `activation.sh` and `deactivation.sh` scripts are run when you enter and leave a `conda` environment.)

**Comment by khallock** [comment]
Hi @fischcheng,

For the conda version of NCL, we implemented a solution for the $NCARG_ROOT environment variable that takes advantage of conda's "source activate $env_name" feature. When NCL is installed into a conda environment, NCARG_ROOT will be set automatically when you activate the environment.

However, if you install NCL into the root conda environment, you'll need to set it manually in your .bashrc (or other appropriate file), for example: 
`export NCARG_ROOT=$HOME/miniconda2`

And as @ocefpaf said, there are no restrictions in this version of NCL -- it should behave the same as the binary-installed version.
