### ISSUE TITLE
Can't install or build ncl

### ISSUE THREAD

**Issue by khallock** [conda-forge/ncl-feedstock#20]
I am currently unable to install and run NCL using existing builds on conda-forge. If I run `conda create -n ncl_test -c conda-forge ncl`, an older build of NCL (6.4.0-3) with a broken `gsl` dependency is installed. If I then install `gsl`, conda also upgrades NCL to the newest version (6.4.0-blas_openblas_4), which unfortunately has its own broken `kealib` dependency.

I read through the build logs on Travis CI for these two NCL builds ([6.4.0-3](https://travis-ci.org/conda-forge/ncl-feedstock/builds/246742910) and [6.4.0-blas_openblas_4](https://travis-ci.org/conda-forge/ncl-feedstock/builds/259469939)) and found that the `gsl=2.2.1=1` package that `ncl=6.4.0=3` was built against is labelled as "[broken](https://anaconda.org/conda-forge/gsl/files?version=2.2.1&channel=broken)", as is [`kealib=1.4.7=2`](https://anaconda.org/conda-forge/kealib/files?version=1.4.7&channel=broken) which is used by both NCL builds.

The only "workaround" I could come up with that allows a user to actually run NCL is to install it with a command like this:
```conda create --name ncl_test3 -c conda-forge -c conda-forge/label/broken ncl gsl=2.2.1=1 kealib=1.4.7=2```

However, I think it would ultimately be a bad idea to suggest using `-c conda-forge/label/broken` to end users.

Unfortunately, I can't even build the recipe on my Mac in order to create a new build without those broken dependencies. It seems as though `cairo` is the culprit, as it's being included as a dependency of `poppler`, which itself was added as a dependency of `libgdal` several months ago. (Note: this issue only affects building NCL on a Mac, the Linux build has always explicitly depended on cairo)

Is there any chance conda-forge/cairo-feedstock#23 will be merged soon? If not, we might have to use non-standard pinning and build NCL against older versions of packages, but that seems like it could be problematic...

**Comment by ocefpaf** [comment]
I guess we can close this now that #21 was merged. Please re-open if that is not true.
