### ISSUE TITLE
Label all NCL builds <6.4.0, <blas_openblas_7 as "broken"

### ISSUE THREAD

**Issue by khallock** [conda-forge/ncl-feedstock#28]
@ocefpaf,

When trying to install the latest build of NCL on Mac, conda keeps trying to use the old `ncl=6.4.0=3` package (which had issues with `gsl`). On Linux, simply running `conda create -n ncl -c conda-forge ncl` works as expected with the new version.

I can get around this by explicitly running `conda create -n ncl -c conda-forge ncl=6.4.0=blas_openblas_7`, but I'd really like a simpler solution without the possibility of installing a broken package.

As far as I can tell, literally every package besides `ncl=6.4.0=blas_openblas_7` is broken due to either runtime linking issues or conda dependency issues. Would it be possible to label those older builds "broken" on [Anaconda Cloud](https://anaconda.org/conda-forge/ncl/files)?

Thanks!

**Comment by ocefpaf** [comment]
Done. Can you double check to see if I got the right ones?

**Comment by khallock** [comment]
Perfect, `conda create -n ncl -c conda-forge ncl` works now!

The 6.3.0 packages are broken too at this point, but it's impossible to accidentally install them so no harm leaving them as "main".

Thanks for all your help today, I really appreciate it!

**Comment by ocefpaf** [comment]
Thank you for taking care of the `ncl` software stack!
